version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shaka-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shaka_db
      POSTGRES_USER: shaka_user
      POSTGRES_PASSWORD: shaka_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: